// This file is auto-generated by scripts/build-themes-mod.ts — do not edit manually.

/**
 * Pre-built {@link ThemeSchema} definitions ready to use with
 * {@link generateThemeCss} or {@link generateThemedCss}.
 *
 * Each theme exports a complete light + dark mode token schema built
 * from the bundled Tailwind color palette.
 *
 * @module
 */

import type { ThemeSchema } from "../types.ts";

/** A complete theme definition with required light mode and optional dark mode. */
export type { ThemeSchema } from "../types.ts";

/** Amber primary / olive accent safari theme — golden warmth with earthy highlights. */
export { default as amberOliveSafari } from "./amber-olive-safari.ts";
/** Blue primary / orange accent theme. */
export { default as blueOrange } from "./blue-orange.ts";
/** Cyan primary / red accent theme. */
export { default as cyanRed } from "./cyan-red.ts";
/** Cyan primary / slate accent theme. */
export { default as cyanSlate } from "./cyan-slate.ts";
/** Emerald primary / amber accent forest theme. */
export { default as emeraldAmberForest } from "./emerald-amber-forest.ts";
/** Emerald primary / pink accent theme. */
export { default as emeraldPink } from "./emerald-pink.ts";
/** Fuchsia primary / emerald accent theme. */
export { default as fuchsiaEmerald } from "./fuchsia-emerald.ts";
/** Neutral gray monochrome theme. */
export { default as gray } from "./gray.ts";
/** Indigo primary / amber accent theme. */
export { default as indigoAmber } from "./indigo-amber.ts";
/** Lime primary / fuchsia accent neon theme. */
export { default as limeFuchsiaNeon } from "./lime-fuchsia-neon.ts";
/** Cool purple-grey mauve monochrome theme. */
export { default as mauve } from "./mauve.ts";
/** Lime primary / fuchsia accent on mauve base — electric contrast on muted purple. */
export { default as mauveLimeElectric } from "./mauve-lime-electric.ts";
/** Mauve primary / teal accent theme — soft purple greys with oceanic highlights. */
export { default as mauveTeal } from "./mauve-teal.ts";
/** Cool blue-grey mist monochrome theme. */
export { default as mist } from "./mist.ts";
/** Indigo primary / sky accent on mist base — cool Nordic fjord tones. */
export { default as mistIndigoFjord } from "./mist-indigo-fjord.ts";
/** Violet primary / cyan accent on mist base — aurora borealis inspired. */
export { default as mistVioletAurora } from "./mist-violet-aurora.ts";
/** Monokai-inspired theme with cyan accent. */
export { default as monokaiCyan } from "./monokai-cyan.ts";
/** Monokai-inspired theme with green accent. */
export { default as monokaiGreen } from "./monokai-green.ts";
/** Monokai-inspired theme with pink accent. */
export { default as monokaiPink } from "./monokai-pink.ts";
/** Warm yellow-grey olive monochrome theme. */
export { default as olive } from "./olive.ts";
/** Olive primary / amber accent safari theme — earthy warmth with golden highlights. */
export { default as oliveAmberSafari } from "./olive-amber-safari.ts";
/** Orange primary / pink accent sunset theme. */
export { default as orangePinkSunset } from "./orange-pink-sunset.ts";
/** Pink primary / emerald accent theme. */
export { default as pinkEmerald } from "./pink-emerald.ts";
/** Pink primary / teal accent theme. */
export { default as pinkTeal } from "./pink-teal.ts";
/** Purple primary / yellow accent theme. */
export { default as purpleYellow } from "./purple-yellow.ts";
/** Multi-color rainbow theme. */
export { default as rainbow } from "./rainbow.ts";
/** Red primary / blue accent theme. */
export { default as redBlue } from "./red-blue.ts";
/** Red primary / cyan accent theme. */
export { default as redCyan } from "./red-cyan.ts";
/** Red primary / sky accent theme. */
export { default as redSky } from "./red-sky.ts";
/** Red primary / sky accent / slate base theme. */
export { default as redSkySlate } from "./red-sky-slate.ts";
/** Rose primary / teal accent theme. */
export { default as roseTeal } from "./rose-teal.ts";
/** Sky primary / amber accent theme. */
export { default as skyAmber } from "./sky-amber.ts";
/** Slate primary / cyan accent theme. */
export { default as slateCyan } from "./slate-cyan.ts";
/** Slate primary / teal accent ocean theme. */
export { default as slateTealOcean } from "./slate-teal-ocean.ts";
/** Neutral stone monochrome theme. */
export { default as stone } from "./stone.ts";
/** Stone primary / orange accent earth theme. */
export { default as stoneOrangeEarth } from "./stone-orange-earth.ts";
/** Warm neutral taupe monochrome theme. */
export { default as taupe } from "./taupe.ts";
/** Taupe primary / olive accent clay theme — all-earthy, warm and grounded. */
export { default as taupeOliveClay } from "./taupe-olive-clay.ts";
/** Rose primary / pink accent on taupe base — warm blush tones. */
export { default as taupeRoseBlush } from "./taupe-rose-blush.ts";
/** Teal primary / rose accent theme. */
export { default as tealRose } from "./teal-rose.ts";
/** Violet primary / lime accent theme. */
export { default as violetLime } from "./violet-lime.ts";
/** Violet primary / rose accent dusk theme. */
export { default as violetRoseDusk } from "./violet-rose-dusk.ts";
/** Neutral zinc monochrome theme. */
export { default as zinc } from "./zinc.ts";

import amberOliveSafari_ from "./amber-olive-safari.ts";
import blueOrange_ from "./blue-orange.ts";
import cyanRed_ from "./cyan-red.ts";
import cyanSlate_ from "./cyan-slate.ts";
import emeraldAmberForest_ from "./emerald-amber-forest.ts";
import emeraldPink_ from "./emerald-pink.ts";
import fuchsiaEmerald_ from "./fuchsia-emerald.ts";
import gray_ from "./gray.ts";
import indigoAmber_ from "./indigo-amber.ts";
import limeFuchsiaNeon_ from "./lime-fuchsia-neon.ts";
import mauve_ from "./mauve.ts";
import mauveLimeElectric_ from "./mauve-lime-electric.ts";
import mauveTeal_ from "./mauve-teal.ts";
import mist_ from "./mist.ts";
import mistIndigoFjord_ from "./mist-indigo-fjord.ts";
import mistVioletAurora_ from "./mist-violet-aurora.ts";
import monokaiCyan_ from "./monokai-cyan.ts";
import monokaiGreen_ from "./monokai-green.ts";
import monokaiPink_ from "./monokai-pink.ts";
import olive_ from "./olive.ts";
import oliveAmberSafari_ from "./olive-amber-safari.ts";
import orangePinkSunset_ from "./orange-pink-sunset.ts";
import pinkEmerald_ from "./pink-emerald.ts";
import pinkTeal_ from "./pink-teal.ts";
import purpleYellow_ from "./purple-yellow.ts";
import rainbow_ from "./rainbow.ts";
import redBlue_ from "./red-blue.ts";
import redCyan_ from "./red-cyan.ts";
import redSky_ from "./red-sky.ts";
import redSkySlate_ from "./red-sky-slate.ts";
import roseTeal_ from "./rose-teal.ts";
import skyAmber_ from "./sky-amber.ts";
import slateCyan_ from "./slate-cyan.ts";
import slateTealOcean_ from "./slate-teal-ocean.ts";
import stone_ from "./stone.ts";
import stoneOrangeEarth_ from "./stone-orange-earth.ts";
import taupe_ from "./taupe.ts";
import taupeOliveClay_ from "./taupe-olive-clay.ts";
import taupeRoseBlush_ from "./taupe-rose-blush.ts";
import tealRose_ from "./teal-rose.ts";
import violetLime_ from "./violet-lime.ts";
import violetRoseDusk_ from "./violet-rose-dusk.ts";
import zinc_ from "./zinc.ts";

/** Kebab-case theme names matching the generated CSS filenames (without extension). */
export const themeNames = [
	"amber-olive-safari",
	"blue-orange",
	"cyan-red",
	"cyan-slate",
	"emerald-amber-forest",
	"emerald-pink",
	"fuchsia-emerald",
	"gray",
	"indigo-amber",
	"lime-fuchsia-neon",
	"mauve",
	"mauve-lime-electric",
	"mauve-teal",
	"mist",
	"mist-indigo-fjord",
	"mist-violet-aurora",
	"monokai-cyan",
	"monokai-green",
	"monokai-pink",
	"olive",
	"olive-amber-safari",
	"orange-pink-sunset",
	"pink-emerald",
	"pink-teal",
	"purple-yellow",
	"rainbow",
	"red-blue",
	"red-cyan",
	"red-sky",
	"red-sky-slate",
	"rose-teal",
	"sky-amber",
	"slate-cyan",
	"slate-teal-ocean",
	"stone",
	"stone-orange-earth",
	"taupe",
	"taupe-olive-clay",
	"taupe-rose-blush",
	"teal-rose",
	"violet-lime",
	"violet-rose-dusk",
	"zinc",
] as const;

/** Map of all bundled themes keyed by camelCase name. Safe to iterate. */
export const bundledThemes: Readonly<Record<string, ThemeSchema>> = {
	amberOliveSafari: amberOliveSafari_,
	blueOrange: blueOrange_,
	cyanRed: cyanRed_,
	cyanSlate: cyanSlate_,
	emeraldAmberForest: emeraldAmberForest_,
	emeraldPink: emeraldPink_,
	fuchsiaEmerald: fuchsiaEmerald_,
	gray: gray_,
	indigoAmber: indigoAmber_,
	limeFuchsiaNeon: limeFuchsiaNeon_,
	mauve: mauve_,
	mauveLimeElectric: mauveLimeElectric_,
	mauveTeal: mauveTeal_,
	mist: mist_,
	mistIndigoFjord: mistIndigoFjord_,
	mistVioletAurora: mistVioletAurora_,
	monokaiCyan: monokaiCyan_,
	monokaiGreen: monokaiGreen_,
	monokaiPink: monokaiPink_,
	olive: olive_,
	oliveAmberSafari: oliveAmberSafari_,
	orangePinkSunset: orangePinkSunset_,
	pinkEmerald: pinkEmerald_,
	pinkTeal: pinkTeal_,
	purpleYellow: purpleYellow_,
	rainbow: rainbow_,
	redBlue: redBlue_,
	redCyan: redCyan_,
	redSky: redSky_,
	redSkySlate: redSkySlate_,
	roseTeal: roseTeal_,
	skyAmber: skyAmber_,
	slateCyan: slateCyan_,
	slateTealOcean: slateTealOcean_,
	stone: stone_,
	stoneOrangeEarth: stoneOrangeEarth_,
	taupe: taupe_,
	taupeOliveClay: taupeOliveClay_,
	taupeRoseBlush: taupeRoseBlush_,
	tealRose: tealRose_,
	violetLime: violetLime_,
	violetRoseDusk: violetRoseDusk_,
	zinc: zinc_,
};

/** All bundled theme names (camelCase). */
export const bundledThemeNames: readonly string[] = Object.keys(bundledThemes);

/** Look up a bundled theme by camelCase name. Returns undefined if unknown. */
export function getBundledTheme(name: string): ThemeSchema | undefined {
	return bundledThemes[name];
}
