import { join } from "@std/path";

const THEMES_DIR = "src/themes";
const MOD_FILE = join(THEMES_DIR, "mod.ts");

/** kebab-case → camelCase */
function toCamelCase(s: string): string {
	return s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

// Discover theme files (exclude mod.ts and _-prefixed internals)
const entries: { kebab: string; camel: string; jsdoc: string }[] = [];

for await (const entry of Deno.readDir(THEMES_DIR)) {
	if (
		!entry.isFile ||
		!entry.name.endsWith(".ts") ||
		entry.name === "mod.ts" ||
		entry.name.startsWith("_")
	) {
		continue;
	}

	const kebab = entry.name.replace(/\.ts$/, "");
	const camel = toCamelCase(kebab);

	// Extract JSDoc above `export default`
	const content = await Deno.readTextFile(join(THEMES_DIR, entry.name));
	const match = content.match(/(\/\*\*[^]*?\*\/)\s*\nexport default/);
	const jsdoc = match?.[1] ?? `/** ${kebab} theme. */`;

	entries.push({ kebab, camel, jsdoc });
}

entries.sort((a, b) => a.kebab.localeCompare(b.kebab));

// Generate mod.ts
const lines: string[] = [
	`// This file is auto-generated by scripts/build-themes-mod.ts — do not edit manually.`,
	``,
	`/**`,
	` * Pre-built {@link ThemeSchema} definitions ready to use with`,
	` * {@link generateThemeCss} or {@link generateThemedCss}.`,
	` *`,
	` * Each theme exports a complete light + dark mode token schema built`,
	` * from the bundled Tailwind color palette.`,
	` *`,
	` * @module`,
	` */`,
	``,
	`import type { ThemeSchema } from "../types.ts";`,
	``,
	`/** A complete theme definition with required light mode and optional dark mode. */`,
	`export type { ThemeSchema } from "../types.ts";`,
	``,
];

for (const { kebab, camel, jsdoc } of entries) {
	lines.push(`${jsdoc}`);
	lines.push(
		`export { default as ${camel} } from "./${kebab}.ts";`,
	);
}

// Build a camelCase import + registry map inline so the registry has no
// runtime dependency on this module's own export namespace (avoids ESM
// circular-import surprises).
lines.push(``);
for (const { kebab, camel } of entries) {
	lines.push(`import ${camel}_ from "./${kebab}.ts";`);
}

lines.push(``);
lines.push(
	`/** Kebab-case theme names matching the generated CSS filenames (without extension). */`,
);
lines.push(`export const themeNames = [`);
for (const { kebab } of entries) {
	lines.push(`\t"${kebab}",`);
}
lines.push(`] as const;`);

lines.push(``);
lines.push(
	`/** Map of all bundled themes keyed by camelCase name. Safe to iterate. */`,
);
lines.push(`export const bundledThemes: Readonly<Record<string, ThemeSchema>> = {`);
for (const { camel } of entries) {
	lines.push(`\t${camel}: ${camel}_,`);
}
lines.push(`};`);

lines.push(``);
lines.push(
	`/** All bundled theme names (camelCase). */`,
);
lines.push(
	`export const bundledThemeNames: readonly string[] = Object.keys(bundledThemes);`,
);

lines.push(``);
lines.push(
	`/** Look up a bundled theme by camelCase name. Returns undefined if unknown. */`,
);
lines.push(
	`export function getBundledTheme(name: string): ThemeSchema | undefined {`,
);
lines.push(`\treturn bundledThemes[name];`);
lines.push(`}`);
lines.push(``);

await Deno.writeTextFile(MOD_FILE, lines.join("\n"));

// Format with deno fmt
const cmd = new Deno.Command("deno", { args: ["fmt", MOD_FILE] });
await cmd.output();

console.log(
	`Generated ${MOD_FILE} with ${entries.length} themes.`,
);
